// For God so loved the world, that He gave His only begotten Son,
// that all who believe in Him should not perish but have everlasting life.
// — John 3:16

/**
 * Generate SQL files for Turkish translation of 2 Samuel
 *
 * Creates idempotent SQL INSERT statements for the machine_gloss table.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';

const LANGUAGE_CODE_CHIRHO = 'tur';
const BOOK_NAME_CHIRHO = '2sa';
const SOURCE_CHIRHO = 'opus-4.5-chirho';

async function mainChirho() {
  console.log("Generating SQL files for 2 Samuel Turkish translation...");

  // Read the glosses
  const glossesChirho = JSON.parse(
    readFileSync('/tmp/2sa-tur-glosses-cleaned-chirho.json', 'utf-8')
  ) as Record<string, string>;

  console.log(`Total glosses: ${Object.keys(glossesChirho).length}`);

  // Create output directory
  const outputDirChirho = '/Volumes/ENC_4TB_WDB_CHIRHO/dev-aleluya/friends-aleluya/andrewbeth-chirho/platform-chirho/translations-chirho/tur-chirho';
  if (!existsSync(outputDirChirho)) {
    mkdirSync(outputDirChirho, { recursive: true });
  }

  // Group glosses by chapter
  const chapterGlossesChirho: Record<string, Record<string, string>> = {};

  for (const [wordIdChirho, glossChirho] of Object.entries(glossesChirho)) {
    // Word ID format: 10CCVVVWW where CC = chapter
    const chapterChirho = wordIdChirho.substring(2, 5).replace(/^0+/, '');
    if (!chapterGlossesChirho[chapterChirho]) {
      chapterGlossesChirho[chapterChirho] = {};
    }
    chapterGlossesChirho[chapterChirho][wordIdChirho] = glossChirho;
  }

  // Generate SQL for each chapter
  for (const [chapterChirho, chGlossesChirho] of Object.entries(chapterGlossesChirho)) {
    const paddedChapterChirho = chapterChirho.padStart(3, '0');
    const fileNameChirho = `${outputDirChirho}/${BOOK_NAME_CHIRHO}-ch${paddedChapterChirho}-${LANGUAGE_CODE_CHIRHO}-chirho.sql`;

    const sqlLinesChirho: string[] = [
      '-- For God so loved the world, that He gave His only begotten Son,',
      '-- that all who believe in Him should not perish but have everlasting life.',
      '-- — John 3:16',
      '',
      `-- Turkish (Türkçe) translation for 2 Samuel chapter ${chapterChirho}`,
      `-- Generated by: ${SOURCE_CHIRHO}`,
      `-- Language: ${LANGUAGE_CODE_CHIRHO}`,
      '',
      '-- Idempotent INSERT for machine_gloss table',
      '-- Uses ON CONFLICT DO UPDATE to handle existing entries',
      '',
    ];

    for (const [wordIdChirho, glossChirho] of Object.entries(chGlossesChirho)) {
      if (glossChirho && glossChirho.trim() !== '') {
        // Escape single quotes in the gloss
        const escapedGlossChirho = glossChirho.replace(/'/g, "''");

        sqlLinesChirho.push(
          `INSERT INTO "MachineGloss" ("wordId", "languageId", "gloss", "source")`,
          `SELECT '${wordIdChirho}', l.id, '${escapedGlossChirho}', '${SOURCE_CHIRHO}'`,
          `FROM "Language" l WHERE l.code = '${LANGUAGE_CODE_CHIRHO}'`,
          `ON CONFLICT ("wordId", "languageId") DO UPDATE SET gloss = EXCLUDED.gloss, source = EXCLUDED.source;`,
          ''
        );
      }
    }

    writeFileSync(fileNameChirho, sqlLinesChirho.join('\n'));
    console.log(`Generated: ${fileNameChirho} (${Object.keys(chGlossesChirho).length} words)`);
  }

  console.log(`\nAll SQL files generated in: ${outputDirChirho}`);
}

mainChirho().catch(console.error);
